### ISSUE TITLE
Two Factor Auth

### ISSUE THREAD

**Issue by tbrenci** [lukecyca/python-instagram-upload#11]
With the new addition of two factor authentication this method appears to be unusable.  The two factor seems to be mandatory as well and I'd imagine that the only way to prompt a 2factor pw to be sent is through an official api call.. which would require a dev key... which would be removed the second they see what you're doing with it.

**Comment by lukecyca** [comment]
Indeed, Instagram has deprecated the API calls we were using. I doubt that anyone has reverse engineered a new method. I certainly don't have a solution.

I have updated the README with a note that this library no longer works.
