### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by sholoma** [lukecyca/python-instagram-upload#12]
Not working uploading photos any more with error
{u'status': u'fail', u'message': u'Please update your Instagram app to continue posting photos'}

**Comment by luctuymans** [comment]
I have the same problem.

**Comment by samayool** [comment]
same problem  ! it seems it is because of the old version of SIG ...

**Comment by lukecyca** [comment]
Indeed, Instagram has deprecated the API calls we were using. I doubt that anyone has reverse engineered a new method. I certainly don't have a solution.

I have updated the README with a note that this library no longer works.
