### ISSUE TITLE
NOT WORKING INSTAGRAM OUT OF DATE ERROR

### ISSUE THREAD

**Issue by samayool** [lukecyca/python-instagram-upload#13]
I  cannot Login anymore ...

{u'status': u'fail', u'message': u'Your version of Instagram is out of date. Please upgrade your app to log in to Instagram.'}

HELP HELP...

**Comment by lukecyca** [comment]
Indeed, Instagram has deprecated the API calls we were using. I doubt that anyone has reverse engineered a new method. I certainly don't have a solution.

I have updated the README with a note that this library no longer works.
